-- MySQL Script generated by MySQL Workbench
-- Model Duendes Site    Version 1.0
-- Description Sistema de Centralização de Vendas de Eventos - Duendes Party

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_duendes_site
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_duendes_site` DEFAULT CHARACTER SET utf8;
USE `bd_duendes_site` ;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`Usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `nome_usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tipo_usuario` VARCHAR(20) NOT NULL DEFAULT 'participante',
  `telefone` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`Organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`Organizador` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf_cnpj` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`Evento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `local` VARCHAR(100) NOT NULL,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `Organizador_ID` INT NOT NULL,
  `imagem_url` VARCHAR(255) NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_Evento_Organizador1_idx` (`Organizador_ID` ASC),
  CONSTRAINT `fk_Evento_Organizador1`
    FOREIGN KEY (`Organizador_ID`)
    REFERENCES `bd_duendes_site`.`Organizador` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`Atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`Atividades` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `data` DATE NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `horario_fim` TIME NOT NULL,
  `convidado` VARCHAR(100) NOT NULL,
  `Evento_ID` INT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_Atividades_Evento1_idx` (`Evento_ID` ASC),
  CONSTRAINT `fk_Atividades_Evento1`
    FOREIGN KEY (`Evento_ID`)
    REFERENCES `bd_duendes_site`.`Evento` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`Inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`Inscricao_Evento` ( 
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Usuario_ID` INT NOT NULL,
  `Evento_ID` INT NOT NULL,
  `data_inscricao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(20) NOT NULL DEFAULT 'confirmada',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `unique_inscricao` (`Usuario_ID` ASC, `Evento_ID` ASC),
  INDEX `fk_Inscricao_Usuario_idx` (`Usuario_ID` ASC),
  INDEX `fk_Inscricao_Evento_idx` (`Evento_ID` ASC),
  CONSTRAINT `fk_Inscricao_Usuario`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `bd_duendes_site`.`Usuario` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Inscricao_Evento`
    FOREIGN KEY (`Evento_ID`)
    REFERENCES `bd_duendes_site`.`Evento` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;