-- MySQL Script generated by MySQL Workbench
-- Model: Duendes Site Model    Version: 2.0
-- Description: Sistema de Centralização de Vendas de Eventos - Duendes Party
-- Author: Josiel
-- Created: 2025

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_duendes_site
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_duendes_site` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `bd_duendes_site` ;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `tipo_usuario` ENUM('participante', 'organizador', 'admin') NOT NULL DEFAULT 'participante',
  `telefone` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `idx_usuario_ativo` (`ativo` ASC),
  INDEX `idx_usuario_tipo` (`tipo_usuario` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`organizadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`organizadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `nome_empresa` VARCHAR(100) NOT NULL,
  `cpf_cnpj` VARCHAR(20) NOT NULL,
  `telefone_comercial` VARCHAR(20) NULL,
  `endereco` VARCHAR(200) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` VARCHAR(2) NULL,
  `biografia` TEXT NULL,
  `website` VARCHAR(255) NULL,
  `instagram` VARCHAR(100) NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `verificado` TINYINT(1) NOT NULL DEFAULT 0,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC),
  INDEX `fk_organizadores_usuarios_idx` (`usuario_id` ASC),
  INDEX `idx_organizador_verificado` (`verificado` ASC),
  INDEX `idx_organizador_ativo` (`ativo` ASC),
  CONSTRAINT `fk_organizadores_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_duendes_site`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `icone` VARCHAR(50) NULL,
  `cor` VARCHAR(7) NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `idx_categoria_ativo` (`ativo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `local` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(200) NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `duracao` INT NULL COMMENT 'Duração em minutos',
  `categoria_id` INT NOT NULL,
  `organizador_id` INT NOT NULL,
  `imagem_url` VARCHAR(255) NULL,
  `capacidade_maxima` INT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT 0.00,
  `destaque` TINYINT(1) NOT NULL DEFAULT 0,
  `publicado` TINYINT(1) NOT NULL DEFAULT 0,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_categorias_idx` (`categoria_id` ASC),
  INDEX `fk_eventos_organizadores_idx` (`organizador_id` ASC),
  INDEX `idx_evento_data` (`data` ASC),
  INDEX `idx_evento_cidade` (`cidade` ASC),
  INDEX `idx_evento_estado` (`estado` ASC),
  INDEX `idx_evento_destaque` (`destaque` ASC),
  INDEX `idx_evento_publicado` (`publicado` ASC),
  INDEX `idx_evento_ativo` (`ativo` ASC),
  CONSTRAINT `fk_eventos_categorias`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `bd_duendes_site`.`categorias` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eventos_organizadores`
    FOREIGN KEY (`organizador_id`)
    REFERENCES `bd_duendes_site`.`organizadores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`atividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `data` DATE NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `horario_fim` TIME NOT NULL,
  `convidado` VARCHAR(100) NOT NULL,
  `biografia_convidado` TEXT NULL,
  `evento_id` INT NOT NULL,
  `ordem` INT NOT NULL DEFAULT 0,
  `local` VARCHAR(100) NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_eventos_idx` (`evento_id` ASC),
  INDEX `idx_atividade_data` (`data` ASC),
  INDEX `idx_atividade_ordem` (`ordem` ASC),
  INDEX `idx_atividade_ativo` (`ativo` ASC),
  CONSTRAINT `fk_atividades_eventos`
    FOREIGN KEY (`evento_id`)
    REFERENCES `bd_duendes_site`.`eventos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`inscricoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`inscricoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `evento_id` INT NOT NULL,
  `data_inscricao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('pendente', 'confirmada', 'cancelada', 'presente') NOT NULL DEFAULT 'confirmada',
  `qr_code` VARCHAR(255) NULL,
  `codigo_ingresso` VARCHAR(20) NULL,
  `checkin_realizado` TINYINT(1) NOT NULL DEFAULT 0,
  `data_checkin` TIMESTAMP NULL,
  `avaliacao` TINYINT(1) NULL COMMENT 'Avaliação de 1 a 5',
  `comentario` TEXT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_inscricao` (`usuario_id` ASC, `evento_id` ASC),
  INDEX `fk_inscricoes_usuarios_idx` (`usuario_id` ASC),
  INDEX `fk_inscricoes_eventos_idx` (`evento_id` ASC),
  INDEX `idx_inscricao_status` (`status` ASC),
  INDEX `idx_inscricao_data` (`data_inscricao` ASC),
  INDEX `idx_inscricao_checkin` (`checkin_realizado` ASC),
  CONSTRAINT `fk_inscricoes_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_duendes_site`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricoes_eventos`
    FOREIGN KEY (`evento_id`)
    REFERENCES `bd_duendes_site`.`eventos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `bd_duendes_site`.`notificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_duendes_site`.`notificacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `tipo` ENUM('info', 'success', 'warning', 'error') NOT NULL DEFAULT 'info',
  `lida` TINYINT(1) NOT NULL DEFAULT 0,
  `data_envio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_leitura` TIMESTAMP NULL,
  `link` VARCHAR(255) NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_notificacoes_usuarios_idx` (`usuario_id` ASC),
  INDEX `idx_notificacao_lida` (`lida` ASC),
  INDEX `idx_notificacao_data` (`data_envio` ASC),
  CONSTRAINT `fk_notificacoes_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_duendes_site`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Data insertion for default categories
-- -----------------------------------------------------
INSERT INTO `bd_duendes_site`.`categorias` (`nome`, `descricao`, `icone`, `cor`) VALUES
('Acadêmico', 'Eventos universitários, palestras, workshops acadêmicos', 'graduation-cap', '#4CAF50'),
('Cultural', 'Shows, teatros, exposições, festivais culturais', 'music', '#9C27B0'),
('Esportivo', 'Competições, maratonas, eventos esportivos', 'trophy', '#FF9800'),
('Corporativo', 'Conferências, feiras de negócios, networking', 'briefcase', '#2196F3'),
('Social', 'Festas, encontros, confraternizações', 'users', '#E91E63'),
('Tecnologia', 'Hackathons, meetups tech, lançamentos', 'code', '#00BCD4'),
('Gastronômico', 'Festivais de comida, degustações, workshops culinários', 'utensils', '#FF5722'),
('Beneficente', 'Eventos para arrecadação, voluntariado', 'heart', '#F44336');

-- -----------------------------------------------------
-- Create admin user
-- -----------------------------------------------------
INSERT INTO `bd_duendes_site`.`usuarios` (`nome`, `cpf`, `usuario`, `email`, `tipo_usuario`, `telefone`, `senha`) 
VALUES ('Administrador', '000.000.000-00', 'admin', 'admin@duendessite.com', 'admin', '(00) 00000-0000', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhf8fVX32AeRyE8KKOk');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;